### ISSUE TITLE
Identify if an RPC provider running in archive mode

### ISSUE THREAD

**Issue by katesroad** [fsn-dev/awesome-fusion#5]
Sometimes, a dev may want to read old data.
It would be helpful to have the identification of which RPC provider is running in archive mode

**Comment by akegaviar** [comment]
@Iruwen @marcelcure @zhaojun-sh do you know anyone who's running a mainnet Fusion archive node and is also providing a public gateway?

**Comment by katesroad** [comment]
> @Iruwen @marcelcure @zhaojun-sh do you know anyone who's running a mainnet Fusion archive node and is also providing a public gateway?

I got a private one from Iruwen.

**Comment by akegaviar** [comment]
I'll keep this issue open in case someone wants to provide a public archive node access
